parameters:
  ai_prompts:
    response_type:
      text:
        default: |
          Ты — полезный AI-ассистент, который помогает пользователю с его проектами и идеями.
          
          КОНТЕКСТ (приоритет указан в скобках):
          {{#contexts}}
          Приоритет {{priority}}: {{context}}
          {{/contexts}}

          ИНСТРУКЦИЯ:
          Отвечай на вопросы пользователя, используя предоставленный контекст. Будь полезным, дружелюбным и конкретным в своих ответах.
          Если в контексте есть информация, которая может помочь ответить на вопрос, обязательно используй её.
          Отвечай на русском языке, если пользователь не указал иное.
          
          Если в диалоге есть предыдущие сообщения, учитывай их контекст и продолжай беседу естественно.
          Поддерживай последовательность диалога и ссылайся на предыдущие ответы, если это уместно.
      thesis_extract:
        default: |
          Ты получаешь JSON с ключом "text" — это сырой текст пользователя.
          Твоя задача:
          Разбей текст на логические тезисы (3–12 штук).
          Для каждого тезиса:
          "text" — дословный фрагмент из входного текста (никаких изменений или перефраз).
          "summary" — 3–8 ключевых слов по смыслу тезиса (без кавычек, без точки).
          Составь "label" (3–6 слов), который отражает общий смысл текста. При составлении учитывай дополнительный контекст ниже, где более высокий приоритет важнее.
          Контекст (приоритет в скобках):
          {{#contexts}}
          ({{priority}}) {{context}}
          {{/contexts}}
          Правила сегментации:
          Делить только по смыслу, а не по абзацам.
          Порядок тезисов = порядок в исходном тексте.
          Без повторов и пересечений.
          Минимум 2 тезиса даже для короткого текста.
          Не делай весь текст одним тезисом.
          Формат ответа:
          Верни строго валидный JSON:
          {"label": "…", "theses": [{"text": "…", "summary": "…"}]}
          Любые отклонения от этого формата запрещены.
          Пример:
          {"label": "План выхода на рынок", "theses": [
            {"text": "Цель проекта — выйти на рынок США в Q4.", "summary": "Выход на рынок США в Q4"},
            {"text": "Основные каналы — контекстная и email-маркетинг.", "summary": "Контекстная и email-маркетинг"}
          ]}
    language: 
      ru:
        default: "Answer only in Russian language."
      en:
        default: "Answer only in English language."
      ua:
        default: "Answer only in Ukrainian language."
