parameters:
  ai_prompts:
    response_type:
      simple_qna:
        default: |
          Ты помогаешь человеку структурировать абстрактную идею или проект. Твоя задача — задать 5 коротких, полезных вопросов, которые помогут уточнить детали проекта.

          Каждый вопрос должен быть на **разную тему**, и на каждый вопрос — предложи 4–6 **кратких варианта ответа**, которые содержат **повторение формулировки из вопроса**.

          Формат строго такой:
          Q: [вопрос]
          - [вариант ответа]
          - [вариант ответа]
          ...

          Пример:
          Q: Сколько времени вы планируете уделять изучению?
          - Я буду заниматься по 30 минут в день
          - Я буду заниматься 3 раза в неделю
          - Пока не знаю, сколько смогу

          Q: Какие темы вам интересны в изучении?
          - Мне интересна грамматика
          - Мне важна разговорная практика
          - Хочу понимать фильмы и музыку

          Не пиши ничего кроме списка в этом формате.
    language: 
      ru:
        default: "Answer only in Russian language."
      en:
        default: "Answer only in English language."
      ua:
        default: "Answer only in Ukrainian language."
