parameters:
  ai_prompts:
    response_type:
      simple_qna:
        default: |
          Ты помогаешь человеку структурировать абстрактную идею или проект. Твоя задача — задать 5 коротких, полезных вопросов, которые помогут уточнить детали проекта.

          Каждый вопрос должен быть на **разную тему**, и на каждый вопрос — предложи 4–6 **кратких варианта ответа**, которые содержат **повторение формулировки из вопроса**.

          Формат строго такой:
          Q: [вопрос]
          - [вариант ответа]
          - [вариант ответа]
          ...

          Пример:
          Q: Сколько времени вы планируете уделять изучению?
          - Я буду заниматься по 30 минут в день
          - Я буду заниматься 3 раза в неделю

          Q: Какие темы вам интересны в изучении?
          - Мне интересна грамматика
          - Мне важна разговорная практика
          - Хочу понимать фильмы и музыку

          Не пиши ничего кроме списка в этом формате.
      thesis_extract:
        default: |
          Вход: ниже будет JSON с ключом "text". В нём — сырой исходный текст пользователя.
          Твоя задача: разбей его на логически связанные тезисы и для каждого тезиса сделай сверхкраткое резюме.
          Также верни короткий заголовок узла (3–6 слов), кратко отражающий суть текста.

          КОНТЕКСТ (приоритет указан в скобках):
          {{#contexts}}
          Приоритет {{priority}}: {{context}}
          {{/contexts}}

          ИНСТРУКЦИЯ:
          Требования к сегментации:
          - Режь только по смыслу, а не по абзацам.
          - Каждый тезис — непрерывный фрагмент исходного текста.
          - Поле "text" в ответе — ПОЛНОЕ ДОСЛОВНОЕ подстрочное совпадение из входного текста (без перефразирования/изменений).
          - Сохраняй порядок появления тезисов. Без перекрытий и дублей.
          - Верни 3–12 тезисов; если текста совсем мало — верни минимум 2.
          - Избегай ситуации, когда весь текст становится одним тезисом.

          Требования к резюме:
          - Поле "summary" — 3–8 самых информативных слов.
          - Без кавычек внутри, без точки в конце.

          Формат ответа: строго валидный JSON‑объект вида {"label": "...", "theses": [{"text": "...", "summary": "..."}, ...]}.
          Если по каким‑то причинам не удаётся вернуть заголовок, всё равно верни поле "label" как пустую строку.

          Пример ответа:
          {"label": "План выхода на рынок", "theses": [
            {"text": "Цель проекта — выйти на рынок США в Q4.", "summary": "Выход на рынок США в Q4"},
            {"text": "Основные каналы — контекстная и email‑маркетинг.", "summary": "Контекстная и email‑маркетинг"}
          ]}
    language: 
      ru:
        default: "Answer only in Russian language."
      en:
        default: "Answer only in English language."
      ua:
        default: "Answer only in Ukrainian language."
